name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
            ssh -o StrictHostKeyChecking=no root@34.72.70.72 "
              sudo su -c 'cd /root/node/bookish-barnacle &&
              git pull origin main &&
              npm install &&
              pm2 restart all'
            "

